### ISSUE TITLE
Password with & symbol

### ISSUE THREAD

**Issue by lucasni2** [idnahacks/GoodHound#40]
Do not use the standard neo4j password and our password contained a & symbol, the password not parsed properly from the parameters and is being seen as a command.

**Comment by idnahacks** [comment]
Sure. There is no input sanitising happening at all. It's intended to be run on the local system so didn't feel like a security concern, however i hadn't considered the operational impact.

Thanks for logging, I'll look to work on that this week.

**Comment by idnahacks** [comment]
In the meantime, try just putting the password in "" quotes.

**Comment by idnahacks** [comment]
Ok, I've looked into this and I think as this is your cli parsing the input the resolution is just to put quotes around the input.
e.g.
```
python goodhound.py -p "neo&4j"
```

I doubt there's anything in the code that can be done to stop your cli from processing the special characters differently as it hasn't actually reached the script at that point.
