### ISSUE TITLE
TypeError: shortestuserpath() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by ztrhgf** [idnahacks/GoodHound#69]
I've tried to run GoodHound but It fails with error 'TypeError: shortestuserpath() missing 1 required positional argument: 'args''
![image](https://user-images.githubusercontent.com/2930419/159510190-a1ac2e08-3196-479a-a358-8a92885b46c3.png)

**Comment by idnahacks** [comment]
Are you running this with data collected using the sharphound version for bloodhound 4.1? If so try with --patch41
https://github.com/idnahacks/GoodHound/wiki/Bloodhound-4.1

Let me know how you get on.

**Comment by idnahacks** [comment]
I believe I've fixed this now with v.1.1.2. I do suspect that if you're getting to the point where it's looking for individual user paths you might be suffering with the Bloodhound 4.1 bug, so worth trying with that --patch41 flag anyway.

Please do let me know if you're still getting the issue, and thanks for logging the bug in the first place :)

**Comment by ztrhgf** [comment]
Yes, I am using BloodHound 4.1.0, but the use of --patch41 didn't help.
![image](https://user-images.githubusercontent.com/2930419/159646505-01523321-19d4-4492-b74e-33ba7777dcc9.png)

**Comment by idnahacks** [comment]
Ok. There was a bug in there that i pushed a fix for yesterday. Can you try getting the latest version and having another go please?
You will need the --patch41 argument when you try again.

**Comment by ztrhgf** [comment]
Nice it is working now!

**Comment by idnahacks** [comment]
Thanks for letting me know
